# Generated by Django 3.2.6 on 2021-08-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32)),
                ('role_definitiion', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('name_extension', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=32)),
                ('civil_status', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.role')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.branch'),
        ),
        migrations.AddField(
            model_name='agent',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.designation'),
        ),
    ]
