# Generated by Django 3.2.6 on 2021-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0002_client_iaccs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('MALE', 'He/Him'), ('FEMALE', 'She/Her'), ('OTHER', 'Other'), ('NOT_SAY', 'Prefer Not To Say')], max_length=32),
        ),
    ]
