# Generated by Django 3.2.6 on 2021-08-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0003_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed/Widower'), ('OTHER', 'Other')], max_length=12),
        ),
    ]
