# Generated by Django 3.2.6 on 2021-08-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0006_alter_credits_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=32)),
                ('tag_description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CutoffPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField()),
                ('auth_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.agent')),
                ('cutoff_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.cutoffperiod')),
                ('encoder_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoder', to='enroller.branch')),
                ('membership_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.branch')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.paymenttype')),
                ('payor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.client')),
                ('premium_paid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.premiumamount')),
                ('tagging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.clienttagging')),
            ],
        ),
    ]
