# Generated by Django 3.2.6 on 2021-09-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0008_client_membership_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='membership_branch',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.PROTECT, to='enroller.branch'),
        ),
    ]
