# Generated by Django 3.2.6 on 2021-09-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0009_alter_client_membership_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='membership_branch',
        ),
    ]
