# Generated by Django 3.2.6 on 2021-09-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0011_client_membership_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payor', to='enroller.client'),
        ),
    ]
