# Generated by Django 3.2.6 on 2021-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0013_auto_20210913_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed/Widower'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'He/Him'), ('FEMALE', 'She/Her'), ('OTHER', 'Other'), ('NOT_SAY', 'Prefer Not To Say')], max_length=32),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
