# Generated by Django 3.2.6 on 2021-09-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0016_alter_agent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
    ]
