# Generated by Django 3.2.6 on 2021-10-13 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0019_alter_agent_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='recording_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
