# Generated by Django 3.2.6 on 2021-10-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0020_auto_20211013_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('APPROVE', 'Approved'), ('CANCEL', 'Cancelled')], max_length=10)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.agent')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enroller.paymentdetails')),
            ],
        ),
    ]
