# Generated by Django 3.2.6 on 2021-10-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0021_paymenttagging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttagging',
            name='tag_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paymenttagging',
            name='tag',
            field=models.CharField(choices=[('APPROVE', 'Approved'), ('CANCEL', 'Cancelled'), ('PENDING', 'Pending')], max_length=10),
        ),
    ]
