# Generated by Django 3.2.6 on 2021-10-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0019_auto_20210925_1203'),
        ('enroller', '0022_auto_20211020_1020'),
    ]

    operations = [
    ]
